version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - ui
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - '3000:80'
